### ISSUE TITLE
OnTestCaseStart is not persisted

### ISSUE THREAD

**Issue by ianwilk20** [microsoft/PowerApps-Language-Tooling#301] opened 2021-08-05 15:20 UTC
Problem: OnTestCaseStart's are not saved after extraction using PowerApps-Language-Tooling

Steps to reproduce:

1. Create a suite in Test Studio
2. Set an OnTestCaseStart property
3. Save the Test Studio Session
4. Save the .msapp file to your computer
5. Unpack the .msapp file
6. In a code editor (like VS) try to find the OnTestCaseStart property you saved 
7. The property is not saved

Additionally:
8. Pack the src files to a .msapp file
9. Open the .msapp file in PowerApps
10. Open Test Studio
11. Select the suite and verify the OnTestCaseStart property is not saved

Below is an example of a property called "TestAccount" that I set in TestStudio:
![OnTestCaseStart Ex](https://user-images.githubusercontent.com/47506745/128375448-5132335a-f792-4809-805e-6364da68b485.png)

Below is a screenshot in Visual Studio of me searching for "TestAccount" and seeing that the search only returns the places in test cases where I used the property, but the "TestAccount" property isn't saved anywhere:
![Search for TestAccount](https://user-images.githubusercontent.com/47506745/128375380-80a55270-7c9a-4b05-a0e1-a75bf45c08d4.PNG)

**Comment by NavneetThekkumpat** [comment] 2022-02-09 19:00
Hi @ianwilk20,

I followed the steps and tried reproducing the issue with latest version of the standalone tool (and pac) but was unable to reproduce the problem.
Can you please check if this issue still exists?

Thank you

**Comment by NavneetThekkumpat** [comment] 2022-02-18 17:10
Since this seems to be nonreproducible, closing this issue for now.
Please feel free to reopen the issue, if it happens in future.

**Closed by NavneetThekkumpat** 2022-02-18 17:10 UTC
Labels: bug
