### ISSUE TITLE
Pac solution clone failing with error :  Error   PA3013: Property Value Changed

### ISSUE THREAD

**Issue by RajeevPentyala** [microsoft/PowerApps-Language-Tooling#464] opened 2023-02-23 15:40 UTC
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)*

While cloning a Dataverse solution using PAC CLI with following command its failing with " Error   PA3013: Property Value Changed" error.
_pac solution clone -n {Solution_Name} --processCanvasApps true --outputDirectory {Path} --packagetype Both --async_

Please mention if it is reproduced using PAC CLI or PASopa. *(Please mention the version number, if possible)* Its reproducible using PAC CLI.

**To Reproduce**

Trigger Clone command using --packagetype Both --async

Organization ID: 97fc9903-def3-4d10-ae0c-2c0bbb57536a
Unique name: unq97fc9903def34d10ae0c2c0bbb575

**Screenshots**
![image](https://user-images.githubusercontent.com/104883923/220955627-30a723a1-f1c8-45f1-a4a7-de38c91caafc.png)

If applicable, add screenshots of error messages to help explain your problem.

**Additional context**

Add any helpful context on the .msapp like created from teams, contains custom pcf components, etc.

**Comment by tomjschneider** [comment] 2023-02-23 21:55
Hey @RajeevPentyala - it looks like the issue is specific to the app `cat_poweractionspage_68091`. If you have access, would you be willing to share this app with us so we can further troubleshoot? If so, you can send the app to tschneider AT microsoft DOT com and we'll have a look.

**Comment by RajeevPentyala** [comment] 2023-02-24 06:05
@tomjschneider Thanks for the quick reply. "cat_poweractionspage_68091" is a custom page. I will mail you the Dataverse solution with "cat_poweractionspage_68091" component for your investigation.

**Comment by NavneetThekkumpat** [comment] 2023-02-28 16:35
Marking this as 'in next release' and will be completed once changes are in next release of the Power Platform CLI.

**Closed** 2023-04-13 15:02 UTC
Labels: bug, in next release
