### ISSUE TITLE
EditorState.json file generates property "AlignInContainer" that isn't recognized in Studio

### ISSUE THREAD

**Issue by thelilyliu** [microsoft/PowerApps-Language-Tooling#224] opened 2021-05-21 16:15 UTC
In my YAML file, I have a container with some labels inside of it. When I pack the app and upload it to Studio, it complains about Label1.AlignInContainer: "Name isn't valid. This identifier isn't recognized."

The property "AlignInContainer" is being generated in the EditorState.json file by PowerApps-Language-Tooling:

```
"Label1": {
    "DynamicProperties": [
      {
        "Property": {
          "PropertyName": "FillPortions",
          "RuleProviderType": "Unknown"
        },
        "PropertyName": "FillPortions"
      },
      {
        "Property": {
          "PropertyName": "AlignInContainer",
          "RuleProviderType": "Unknown"
        },
        "PropertyName": "AlignInContainer"
      },
      {
        "Property": {
          "PropertyName": "LayoutMinHeight",
          "RuleProviderType": "Unknown"
        },
        "PropertyName": "LayoutMinHeight"
      },
      {
        "Property": {
          "PropertyName": "LayoutMinWidth",
          "RuleProviderType": "Unknown"
        },
        "PropertyName": "LayoutMinWidth"
      }
    ],
    ...
}
```

However, when I create an app from scratch in Studio, download it, and unpack it, the YAML file is identical, but in the EditorState.json file, there is no occurrence of "AlignInContainer".

```
Screen1 As screen:

    Container1 As groupContainer.manualLayoutContainer:
        DisplayMode: =DisplayMode.Edit
        Height: =768
        LayoutDirection: =LayoutDirection.Horizontal
        LayoutMode: =LayoutMode.Manual
        Width: =1366
        ZIndex: =1

        Label1 As label:
            Text: ="Text 1"
            ZIndex: =1

        Label2 As label:
            Text: ="Text 2"
            Y: =40
            ZIndex: =2

        Label3 As label:
            Text: ="Text 3"
            Y: =80
            ZIndex: =3
```

**Comment by suskumar-MSFT** [comment] 2021-07-15 21:51
Chatter with @thelilyliu, the issue is fixed in the latest code, hence closing.

**Closed by suskumar-MSFT** 2021-07-15 21:51 UTC
Labels: bug
