### ISSUE TITLE
Error   PA3015: Property Removed: AnalysisOptions.DataflowAnalysisEnabled

### ISSUE THREAD

**Issue by jansonjc** [microsoft/PowerApps-Language-Tooling#494] opened 2023-09-12 15:31 UTC
## Describe the bug

The following error is produced while unpacking a canvas app using PAC CLI Version: 1.26.6+ga3cb14b

```
Error: Error   PA3015: Property Removed: AnalysisOptions.DataflowAnalysisEnabled
Error   PA3015: Property Removed: AnalysisOptions.DataflowAnalysisFlagStateToggledByUser
Error   PA3011: Roundtrip validation on unpack failed. 
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
```
The also leaves a `.\diffFiles` folder where the command is executed

### To Reproduce

1. Refer attached msapp - [ucs.zip](https://github.com/microsoft/PowerApps-Language-Tooling/files/12588213/ucs.zip)
2. Unpack the canvas app - pac solution unpack -z ucs.zip -ad -f ../src/powerapps/ucs-solution

**Comment by fowl2** [comment] 2023-09-13 06:24
seems a duplicate of #493

**Comment by Ourps** [comment] 2023-09-13 07:06
It is

**Comment by clairewu0218** [comment] 2023-09-18 19:27
Thanks for providing the information. We are looking into it. Will close as this is a duplicate.

**Closed by clairewu0218** 2023-09-18 19:27 UTC
Labels: duplicate
