### ISSUE TITLE
Unpacking some apps has error: does not have a corresponding data source.

### ISSUE THREAD

**Issue by MikeStall** [microsoft/PowerApps-Language-Tooling#313] opened 2021-10-18 20:52 UTC
Unpacking some apps get this error: 

Error   PA3005: Validation error: Connection '[dbo].[ActivePrimaryNotification]_1' does not have a corresponding data source.
1 errors, 0 warnings.

**Comment by jt000** [comment] 2022-01-28 20:04
Duplicate of #308

**Closed by jt000** 2022-01-28 20:04 UTC
Labels: bug, duplicate
